name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
        
    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@0.2.0
      
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build app and run unit tests
      uses: gradle/gradle-command-action@v2
      with:
        arguments: assembleStandardRelease
      
    - name: Clean up build artifact
      run: |
        set -e
        mv app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned-signed.apk OsuProfile.apk
        cp app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned-signed.apk OsuProfile-arm64-v8a.apk
        cp app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned-signed.apk OsuProfile-armeabi-v7a-.apk
        cp app/build/outputs/apk/standard/release/app-standard-x86-release-unsigned-signed.apk OsuProfile-x86.apk
        cp app/build/outputs/apk/standard/release/app-standard-x86_64-release-unsigned-signed.apk OsuProfile-x86_64.apk

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: OsuProfile
        body: Cringe
        files: |
          OsuProfile.apk
          OsuProfile-arm64-v8a.apk
          OsuProfile-armeabi-v7a.apk
          OsuProfile-x86.apk
          OsuProfile-x86_64.apk
        draft: true
        prerelease: false
